version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
    - BACKEND_SERVER_URL=http://dynamodb:8000
    networks:
      - app-network
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    networks:
      - app-network
    volumes:
    - dynamodb_data:/home/dynamodblocal

volumes:
  dynamodb_data:

networks:
  app-network:
    external: true
